//This file was created via CT-GUI! Editing it is not advised!
//Don't touch me!
//#Remove
recipes.remove(<nuclearcraft:cobblestone_generator>);
recipes.remove(<projecte:collector_mk2>);
recipes.remove(<projecte:collector_mk3>);
recipes.remove(<projecte:collector_mk1>);
recipes.remove(<projecte:collector_mk1>);
recipes.remove(<enderio:item_me_conduit>);
recipes.remove(<enderio:item_redstone_conduit>);
recipes.remove(<enderio:item_liquid_conduit:2>);
recipes.remove(<enderio:item_liquid_conduit:1>);
recipes.remove(<enderio:item_liquid_conduit>);
recipes.remove(<aether:skyroot_chest>);
recipes.remove(<extrautils2:angelring:1>);
recipes.remove(<extrautils2:angelring:5>);
recipes.remove(<extrautils2:angelring:4>);
recipes.remove(<extrautils2:angelring:3>);
recipes.remove(<extrautils2:angelring:2>);
recipes.remove(<projecte:item.pe_swrg>);
recipes.remove(<nuclearcraft:cobblestone_generator_dense>);
recipes.remove(<nuclearcraft:cobblestone_generator_compact>);
recipes.remove(<minecraft:piston>);
recipes.remove(<skylandsutilities:holystone_stick>);
recipes.remove(<projecte:item.pe_repair_talisman>);
recipes.remove(<chiselsandbits:wrench_wood>);
recipes.remove(<quantumstorage:quantum_battery>);
recipes.remove(<quantumstorage:quantum_storage_unit>);
recipes.remove(<quantumstorage:quantum_tank>);
recipes.remove(<quantumstorage:chest_diamond>);
recipes.remove(<quantumstorage:chest_gold>);
recipes.remove(<quantumstorage:chest_iron>);
recipes.remove(<appliedenergistics2:material:54>);
recipes.remove(<appliedenergistics2:material:35>);
recipes.remove(<draconicevolution:fusion_crafting_core>);
recipes.remove(<nuclearcraft:reactor_casing_transparent> * 4);
recipes.remove(<nuclearcraft:fission_block> * 4);
recipes.remove(<nuclearcraft:fission_controller_new_idle>);
recipes.remove(<draconicevolution:crafting_injector>);
recipes.remove(<appliedenergistics2:material:57>);
recipes.remove(<appliedenergistics2:material:56>);
recipes.remove(<appliedenergistics2:material:55>);
recipes.remove(<appliedenergistics2:material:38>);
recipes.remove(<appliedenergistics2:material:37>);
recipes.remove(<appliedenergistics2:material:36>);
recipes.remove(<extrautils2:machine>.withTag({Type: "extrautils2:generator_netherstar"}));
recipes.remove(<wct:wct>);
recipes.remove(<mysticalagriculture:void_metal_seeds>);
recipes.remove(<translocators:translocator_part>);
recipes.remove(<projecte:item.pe_time_watch>);
recipes.remove(<projecte:condenser_mk1>);
recipes.remove(<projecte:item.pe_gem_armor_1>);
recipes.remove(<redstonefluxarsenal:rfenergizedarmour.chestplate>);
recipes.remove(<redstonefluxarsenal:itemrfsword>);
recipes.remove(<redstonefluxarsenal:itemrfhoe>);
recipes.remove(<redstonefluxarsenal:rfenergizedarmour.helmet>);
recipes.remove(<redstonefluxarsenal:rfenergizedarmour.leggings>);
recipes.remove(<redstonefluxarsenal:rfenergizedarmour.boots>);
recipes.remove(<projecte:condenser_mk2>);
recipes.remove(<projecte:item.pe_rm_armor_0>);
recipes.remove(<projecte:item.pe_rm_armor_1>);
recipes.remove(<projecte:item.pe_rm_armor_3>);
recipes.remove(<draconicevolution:grinder>);
recipes.remove(<endreborn:armour_boots_obsidian>);
recipes.remove(<endreborn:armour_leggings_obsidian>);
recipes.remove(<endreborn:armour_chestplate_obsidian>);
recipes.remove(<endreborn:armour_helmet_obsidian>);
recipes.remove(<enderio:item_dark_steel_boots>);
recipes.remove(<enderio:item_dark_steel_leggings>);
recipes.remove(<enderio:item_dark_steel_chestplate>);
recipes.remove(<enderio:item_dark_steel_helmet>);
recipes.remove(<enderio:item_end_steel_boots>);
recipes.remove(<enderio:item_end_steel_leggings>);
recipes.remove(<enderio:item_end_steel_chestplate>);
recipes.remove(<enderio:item_end_steel_helmet>);
recipes.remove(<enderio:item_power_conduit:2>);
recipes.remove(<enderio:item_power_conduit:1>);
recipes.remove(<enderio:item_power_conduit>);
recipes.remove(<projecte:item.pe_dm_armor_0>);
recipes.remove(<projecte:item.pe_dm_armor_1>);
recipes.remove(<projecte:item.pe_dm_armor_2>);
recipes.remove(<projecte:item.pe_dm_armor_3>);
recipes.remove(<draconicevolution:wyvern_boots>);
recipes.remove(<draconicevolution:wyvern_chest>);
recipes.remove(<draconicevolution:wyvern_legs>);
recipes.remove(<draconicevolution:wyvern_helm>);
recipes.remove(<draconicevolution:wyvern_pick>);
recipes.remove(<projecte:item.pe_dm_pick>);
recipes.remove(<projecte:item.pe_rm_pick>);
recipes.remove(<appliedenergistics2:drive>);
recipes.remove(<appliedenergistics2:charger>);
recipes.remove(<enderio:block_simple_sag_mill>);
recipes.remove(<storagenetwork:remote:1>);
recipes.remove(<storagenetwork:remote>);
recipes.remove(<simplevoidworld:portal>);
recipes.remove(<appliedenergistics2:material:46>);
recipes.remove(<projecte:item.pe_transmutation_tablet>);
recipes.remove(<minecraft:cauldron>);
recipes.remove(<appliedenergistics2:grindstone>);
recipes.remove(<storagenetwork:master>);
recipes.remove(<storagenetwork:kabel>);
recipes.remove(<storagenetwork:request>);
recipes.remove(<extrautils2:bagofholding>);
recipes.remove(<extrautils2:machine>.withTag({Type: "extrautils2:crusher"}));
recipes.remove(<extrautils2:machine>.withTag({Type: "extrautils2:furnace"}));
recipes.remove(<nuclearcraft:manufactory_idle>);
recipes.remove(<nuclearcraft:alloy_furnace_idle>);
recipes.remove(<nuclearcraft:upgrade>);
recipes.remove(<nuclearcraft:dominos>);
recipes.remove(<projecte:alchemical_chest>);
recipes.remove(<extrautils2:teleporter:1>);
recipes.remove(<enderio:item_material:51>);
recipes.remove(<mysticalagriculture:crafting:32>);
recipes.remove(<projecte:item.pe_rm_armor_2>);
recipes.remove(<mysticalagriculture:supremium_chestplate>);
recipes.remove(<equivalentenergistics:emc_condenser:2>);
recipes.remove(<equivalentenergistics:emc_condenser:3>);
recipes.remove(<equivalentenergistics:emc_condenser:1>);
recipes.remove(<appliedenergistics2:energy_acceptor>);
recipes.remove(<minecraft:furnace>);
recipes.remove(<aether:holystone_furnace>);
recipes.remove(<mysticalagriculture:crafting:16>);
recipes.remove(<extrautils2:angelring>);
recipes.remove(<extrautils2:grocket>);
recipes.remove(<extrautils2:grocket:2>);
recipes.remove(<extrautils2:pipe>);
recipes.remove(<enderio:item_item_conduit>);
recipes.remove(<appliedenergistics2:inscriber>);
recipes.remove(<appliedenergistics2:controller>);
recipes.remove(<excompressum:compressed_block:3>);
recipes.remove(<excompressum:compressed_block:2>);
recipes.remove(<excompressum:compressed_block:1>);
recipes.remove(<exnihilocreatio:block_end_cake>);
recipes.remove(<progressivealchemy:condensertiered_8>);
recipes.remove(<progressivealchemy:condensertiered_7>);
recipes.remove(<progressivealchemy:condensertiered_6>);
recipes.remove(<progressivealchemy:condensertiered_5>);
recipes.remove(<progressivealchemy:condensertiered_4>);
recipes.remove(<progressivealchemy:condensertiered_3>);
recipes.remove(<progressivealchemy:condensertiered_2>);
recipes.remove(<progressivealchemy:condensertiered_1>);
//recipes.remove(<projecte:collector_mk3>);
//recipes.remove(<projecte:collector_mk1>);
//recipes.remove(<projecte:collector_mk2>);
recipes.remove(<projecte:condenser_mk1>);
recipes.remove(<projecte:item.pe_philosophers_stone>);
recipes.remove(<projecte:transmutation_table>);
recipes.remove(<exnihilocreatio:block_crucible_wood>);
//Don't touch me!
//#Add
recipes.addShaped(<draconicevolution:grinder>, [[<extrautils2:ingredients:11>, <enderio:item_material:42>, <extrautils2:ingredients:11>],[<draconicevolution:wyvern_sword:*>, <mob_grinding_utils:saw>, <draconicevolution:wyvern_sword:*>], [<extrautils2:ingredients:11>, <mysticalagriculture:supremium_furnace>, <extrautils2:ingredients:11>]]);
recipes.addShaped(<nuclearcraft:cobblestone_generator>, [[<nuclearcraft:part>, <nuclearcraft:ingot:1>, <nuclearcraft:part>],[<minecraft:lava_bucket>, <enderio:item_material>, <minecraft:water_bucket>], [<nuclearcraft:part>, <nuclearcraft:ingot:1>, <nuclearcraft:part>]]);
recipes.addShaped(<nuclearcraft:cobblestone_generator>, [[<nuclearcraft:part>, <nuclearcraft:ingot:1>, <nuclearcraft:part>],[<minecraft:water_bucket>, <enderio:item_material>, <minecraft:lava_bucket>], [<nuclearcraft:part>, <nuclearcraft:ingot:1>, <nuclearcraft:part>]]);
recipes.addShaped(<nuclearcraft:cobblestone_generator_dense>, [[<nuclearcraft:cobblestone_generator_compact>, <nuclearcraft:cobblestone_generator_compact>, <nuclearcraft:cobblestone_generator_compact>],[<nuclearcraft:cobblestone_generator_compact>, <thaumadditions:adaminite_ingot>, <nuclearcraft:cobblestone_generator_compact>], [<nuclearcraft:cobblestone_generator_compact>, <nuclearcraft:cobblestone_generator_compact>, <nuclearcraft:cobblestone_generator_compact>]]);
recipes.addShaped(<nuclearcraft:cobblestone_generator_compact>, [[<nuclearcraft:cobblestone_generator>, <nuclearcraft:cobblestone_generator>, <nuclearcraft:cobblestone_generator>],[<nuclearcraft:cobblestone_generator>, <thaumadditions:mithrillium_ingot>, <nuclearcraft:cobblestone_generator>], [<nuclearcraft:cobblestone_generator>, <nuclearcraft:cobblestone_generator>, <nuclearcraft:cobblestone_generator>]]);
recipes.addShaped(<projecte:collector_mk1>, [[<enderio:block_alloy:2>, <enderio:block_alloy:2>, <enderio:block_alloy:2>],[<nuclearcraft:cobblestone_generator>, <thaumicbases:thauminite_ingot>, <nuclearcraft:cobblestone_generator>], [<enderio:block_alloy:2>, <projecte:dm_furnace>, <enderio:block_alloy:2>]]);
recipes.addShaped(<projecte:collector_mk2>, [[<enderio:block_alloy:2>, <thaumadditions:mithrillium_ingot>, <enderio:block_alloy:2>],[<enderio:block_alloy:2>, <nuclearcraft:cobblestone_generator_compact>, <enderio:block_alloy:2>], [<enderio:block_alloy:2>, <projecte:collector_mk1>, <enderio:block_alloy:2>]]);
recipes.addShaped(<projecte:collector_mk3>, [[<enderio:block_alloy:2>, <thaumadditions:adaminite_ingot>, <enderio:block_alloy:2>],[<enderio:block_alloy:2>, <nuclearcraft:cobblestone_generator_dense>, <enderio:block_alloy:2>], [<enderio:block_alloy:2>, <projecte:collector_mk2>, <enderio:block_alloy:2>]]);
recipes.addShaped(<enderio:item_me_conduit>, [[<enderio:item_material:4>, <enderio:item_material:4>, <enderio:item_material:4>],[<appliedenergistics2:material:7>, <appliedenergistics2:part:140>, <appliedenergistics2:material:7>], [<enderio:item_material:4>, <enderio:item_material:4>, <enderio:item_material:4>]]);
recipes.addShaped(<enderio:item_redstone_conduit>, [[<enderio:item_material:4>, <enderio:item_material:4>, <enderio:item_material:4>],[<enderio:item_alloy_nugget:3>, <enderio:item_alloy_nugget:3>, <enderio:item_alloy_nugget:3>], [<enderio:item_material:4>, <enderio:item_material:4>, <enderio:item_material:4>]]);
recipes.addShaped(<enderio:item_liquid_conduit:2>, [[<enderio:item_material:4>, <enderio:item_material:4>, <enderio:item_material:4>],[<enderio:item_alloy_ingot:2>, <enderio:block_fused_quartz>, <enderio:item_alloy_ingot:2>], [<enderio:item_material:4>, <enderio:item_material:4>, <enderio:item_material:4>]]);
recipes.addShaped(<enderio:item_liquid_conduit:1>, [[<enderio:item_material:4>, <enderio:item_material:4>, <enderio:item_material:4>],[<enderio:block_fused_quartz>, <enderio:block_fused_quartz>, <enderio:block_fused_quartz>], [<enderio:item_material:4>, <enderio:item_material:4>, <enderio:item_material:4>]]);
recipes.addShaped(<enderio:item_liquid_conduit>, [[<enderio:item_material:4>, <enderio:item_material:4>, <enderio:item_material:4>],[<enderio:block_fused_glass>, <enderio:block_fused_glass>, <enderio:block_fused_glass>], [<enderio:item_material:4>, <enderio:item_material:4>, <enderio:item_material:4>]]);
recipes.addShaped(<extrautils2:angelring:1>, [[<minecraft:feather>, <extrautils2:angelring>, null],[<minecraft:feather>, null, null], [null, null, null]]);
recipes.addShaped(<exnihilocreatio:block_end_cake>, [[<randomthings:stableenderpearl>, <minecraft:ender_eye>, <randomthings:stableenderpearl>],[<randomthings:stableenderpearl>, <enderio:item_material:70>, <randomthings:stableenderpearl>], [<endreborn:item_advanced_ender_pearl>, <chisel:voidstone>, <endreborn:item_advanced_ender_pearl>]]);
recipes.addShaped(<foodfunk:rotted_item>, [[null, null, null],[<composter:compost>, <composter:compost>, <composter:compost>], [null, null, null]]);
recipes.addShaped(<extrautils2:angelring:5>, [[<minecraft:coal>, <extrautils2:angelring>, null],[<minecraft:coal:1>, null, null], [null, null, null]]);
recipes.addShaped(<extrautils2:angelring:4>, [[<minecraft:gold_nugget>, <extrautils2:angelring>, null],[<minecraft:gold_nugget>, null, null], [null, null, null]]);
recipes.addShaped(<extrautils2:angelring:3>, [[<minecraft:leather>, <extrautils2:angelring>, null],[<minecraft:leather>, null, null], [null, null, null]]);
recipes.addShaped(<extrautils2:angelring:2>, [[<minecraft:dye:5>, <extrautils2:angelring>, null],[<minecraft:dye:9>, null, null], [null, null, null]]);
recipes.addShaped(<extrautils2:angelring>, [[<aether:cockatrice_feather>, <thaumadditions:mithrillium_ingot>, <aether:moa_feather>],[<thaumadditions:mithrillium_ingot>, <extrautils2:chickenring:1>, <thaumadditions:mithrillium_ingot>], [<enderio:item_material:19>, <thaumadditions:mithrillium_ingot>, <enderio:item_material:19>]]);
recipes.addShaped(<foodfunk:rotten_food>, [[null, null, null],[<foodfunk:rotted_item>, <foodfunk:rotted_item>, <foodfunk:rotted_item>], [null, null, null]]);
//recipes.addShaped(<foodfunk:rotted_item>, [[null, <composter:compost>, null],[<composter:compost>, <composter:compost>, <composter:compost>], [null, null, null]]);
recipes.addShaped(<csam:terracotta_sword>, [[null, null, null],[null, <minecraft:stick>, <csam:terracotta_sword_head>], [null, <minecraft:stick>, null]]);
recipes.addShaped(<csam:terracotta_shovel>, [[null, null, null],[null, <minecraft:stick>, <csam:terracotta_shovel_head>], [null, <minecraft:stick>, null]]);
recipes.addShaped(<csam:terracotta_hoe>, [[null, null, null],[null, <minecraft:stick>, <csam:terracotta_hoe_head>], [null, <minecraft:stick>, null]]);
recipes.addShaped(<csam:terracotta_axe>, [[null, null, null],[null, <minecraft:stick>, <csam:terracotta_axe_head>], [null, <minecraft:stick>, null]]);
recipes.addShaped(<csam:terracotta_pickaxe>, [[null, null, null],[null, <minecraft:stick>, <csam:terracotta_pickaxe_head>], [null, <minecraft:stick>, null]]);
recipes.addShaped(<projecte:item.pe_swrg>, [[<projecte:item.pe_matter>, <aether:cockatrice_feather>, <projecte:item.pe_matter>],[<aether:cockatrice_feather>, <projecte:item.pe_ring_iron_band>, <aether:cockatrice_feather>], [<projecte:item.pe_matter>, <aether:cockatrice_feather>, <projecte:item.pe_matter>]]);
//recipes.addShaped(<nuclearcraft:cobblestone_generator_dense>, [[<nuclearcraft:cobblestone_generator_compact>, <nuclearcraft:cobblestone_generator_compact>, <nuclearcraft:cobblestone_generator_compact>],[<nuclearcraft:cobblestone_generator_compact>, <nuclearcraft:ingot_oxide:1>, <nuclearcraft:cobblestone_generator_compact>], [<nuclearcraft:cobblestone_generator_compact>, <nuclearcraft:cobblestone_generator_compact>, <nuclearcraft:cobblestone_generator_compact>]]);
//recipes.addShaped(<nuclearcraft:cobblestone_generator_compact>, [[<nuclearcraft:cobblestone_generator>, <nuclearcraft:cobblestone_generator>, <nuclearcraft:cobblestone_generator>],[<nuclearcraft:cobblestone_generator>, <nuclearcraft:ingot_oxide>, <nuclearcraft:cobblestone_generator>], [<nuclearcraft:cobblestone_generator>, <nuclearcraft:cobblestone_generator>, <nuclearcraft:cobblestone_generator>]]);
recipes.addShaped(<skylandsutilities:holystone_stick> * 2, [[null, null, null],[null, <aether:holystone>, null], [null, <aether:holystone>, null]]);
recipes.addShaped(<minecraft:piston>, [[<ore:plankWood>, <ore:plankWood>, <ore:plankWood>],[<appliedenergistics2:smooth_sky_stone_block>, <minecraft:iron_ingot>, <appliedenergistics2:smooth_sky_stone_block>], [<appliedenergistics2:smooth_sky_stone_block>, <minecraft:redstone>, <appliedenergistics2:smooth_sky_stone_block>]]);
recipes.addShaped(<minecraft:furnace>, [[<minecraft:cobblestone>, <minecraft:cobblestone>, <minecraft:cobblestone>],[<minecraft:cobblestone>, <exnihilocreatio:item_material:1>, <minecraft:cobblestone>], [<exnihilocreatio:item_material:1>, <exnihilocreatio:item_material:1>, <exnihilocreatio:item_material:1>]]);
recipes.addShaped(<appliedenergistics2:grindstone>, [[<appliedenergistics2:smooth_sky_stone_block>, <enderio:item_material:10>, <appliedenergistics2:smooth_sky_stone_block>],[<appliedenergistics2:material>, <enderio:item_basic_capacitor>, <appliedenergistics2:material>], [<appliedenergistics2:smooth_sky_stone_block>, <appliedenergistics2:material>, <appliedenergistics2:smooth_sky_stone_block>]]);
recipes.addShaped(<appliedenergistics2:grindstone>, [[<appliedenergistics2:smooth_sky_stone_block>, <enderio:item_material:10>, <appliedenergistics2:smooth_sky_stone_block>],[<minecraft:quartz>, <enderio:item_basic_capacitor>, <minecraft:quartz>], [<appliedenergistics2:smooth_sky_stone_block>, <minecraft:quartz>, <appliedenergistics2:smooth_sky_stone_block>]]);
recipes.addShaped(<progressivealchemy:condensertiered_2>, [[<projecte:item.pe_covalence_dust:1>, <projecte:item.pe_covalence_dust:1>, <projecte:item.pe_covalence_dust:1>],[<appliedenergistics2:sky_stone_block>, <projecte:alchemical_chest>, <appliedenergistics2:sky_stone_block>], [<minecraft:gold_ingot>, <progressivealchemy:condensertiered_1>, <minecraft:gold_ingot>]]);
recipes.addShaped(<progressivealchemy:condensertiered_3>, [[<projecte:item.pe_covalence_dust:2>, <projecte:item.pe_covalence_dust:2>, <projecte:item.pe_covalence_dust:2>],[<appliedenergistics2:sky_stone_block>, <enderio:item_material:43>, <appliedenergistics2:sky_stone_block>], [<thaumcraft:ingot>, <progressivealchemy:condensertiered_2>, <thaumcraft:ingot>]]);
recipes.addShaped(<progressivealchemy:condensertiered_1>, [[<projecte:item.pe_covalence_dust>, <projecte:item.pe_covalence_dust>, <projecte:item.pe_covalence_dust>],[<appliedenergistics2:sky_stone_block>, <enderio:item_basic_capacitor:1>, <appliedenergistics2:sky_stone_block>], [<minecraft:iron_ingot>, <thaumcraft:hungry_chest>, <minecraft:iron_ingot>]]);
//recipes.addShapeless(<skylandsutilities:holystone_stick> * 4, [<ore:holystone>,<ore:holystone>]);
recipes.addShaped(<draconicevolution:crafting_injector>, [[<avaritia:resource>, <draconicevolution:draconic_core>, <avaritia:resource>],[<enderio:block_alloy>, <enderio:item_basic_capacitor:2>, <enderio:block_alloy>], [<enderio:block_alloy>, <enderio:block_alloy>, <enderio:block_alloy>]]);
recipes.addShaped(<projecte:item.pe_repair_talisman>, [[<projecte:item.pe_covalence_dust>, <projecte:item.pe_covalence_dust:1>, <projecte:item.pe_covalence_dust:2>],[<minecraft:string>, <enderio:item_basic_capacitor:2>, <minecraft:string>], [<nuclearcraft:dust_oxide:1>, <nuclearcraft:dust_oxide>, <nuclearcraft:dust_oxide:2>]]);
recipes.addShapeless(<aether:holystone>, [<aether:holystone_rock>,<aether:holystone_rock>,<aether:holystone_rock>,<aether:holystone_rock>]);
recipes.addShaped(<chiselsandbits:wrench_wood>, [[null, <minecraft:planks>, null],[null, <minecraft:planks>, <minecraft:planks>], [<minecraft:stick>, null, null]]);
recipes.addShaped(<quantumstorage:quantum_battery>, [[null, <nuclearcraft:ingot:6>, null],[null, <draconicevolution:wyvern_energy_core>, null], [null, <nuclearcraft:ingot:5>, null]]);
recipes.addShaped(<quantumstorage:quantum_storage_unit>, [[<nuclearcraft:reactor_casing_transparent>, <nuclearcraft:reactor_casing_transparent>, <nuclearcraft:reactor_casing_transparent>],[<nuclearcraft:alloy:4>, <enderutilities:msu>, <nuclearcraft:alloy:4>], [<nuclearcraft:alloy:4>, <nuclearcraft:alloy:4>, <nuclearcraft:alloy:4>]]);
recipes.addShaped(<quantumstorage:quantum_tank>, [[<ore:ingotTough>, <nuclearcraft:alloy:1>, <ore:ingotTough>],[<ore:ingotTough>, <enderio:block_tank:1>, <ore:ingotTough>], [<ore:ingotTough>, <ore:ingotTough>, <ore:ingotTough>]]);
recipes.addShaped(<quantumstorage:chest_iron>, [[<ore:plankWood>, <minecraft:iron_ingot>, <ore:plankWood>],[<ore:plankWood>, <enderio:item_basic_capacitor>, <ore:plankWood>], [<ore:plankWood>, <ore:chest>, <ore:plankWood>]]);
recipes.addShaped(<quantumstorage:chest_diamond>, [[<ore:plankWood>, <minecraft:diamond>, <ore:plankWood>],[<ore:plankWood>, <enderio:item_material:41>, <ore:plankWood>], [<ore:plankWood>, <quantumstorage:chest_gold>, <ore:plankWood>]]);
recipes.addShaped(<quantumstorage:chest_gold>, [[<ore:plankWood>, <minecraft:gold_ingot>, <ore:plankWood>],[<ore:plankWood>, <enderio:item_basic_capacitor:1>, <ore:plankWood>], [<ore:plankWood>, <quantumstorage:chest_iron>, <ore:plankWood>]]);
recipes.addShaped(<nuclearcraft:reactor_casing_transparent> * 4, [[<enderio:block_fused_quartz>, <nuclearcraft:part:1>, <enderio:block_fused_quartz>],[<nuclearcraft:part:1>, <nuclearcraft:alloy:1>, <nuclearcraft:part:1>], [<enderio:block_fused_quartz>, <nuclearcraft:part:1>, <enderio:block_fused_quartz>]]);
recipes.addShaped(<nuclearcraft:fission_block> * 4, [[<nuclearcraft:alloy:1>, <nuclearcraft:part:1>, <nuclearcraft:alloy:1>],[<nuclearcraft:part:1>, null, <nuclearcraft:part:1>], [<nuclearcraft:alloy:1>, <nuclearcraft:part:1>, <nuclearcraft:alloy:1>]]);
recipes.addShaped(<appliedenergistics2:material:54>, [[<nuclearcraft:alloy:1>, <nuclearcraft:part>, <nuclearcraft:alloy:1>],[<nuclearcraft:part>, <appliedenergistics2:material:23>, <nuclearcraft:part>], [<nuclearcraft:alloy:1>, <nuclearcraft:part>, <nuclearcraft:alloy:1>]]);
recipes.addShaped(<appliedenergistics2:material:57>, [[<nuclearcraft:alloy:1>, <appliedenergistics2:material:23>, <nuclearcraft:alloy:1>],[<appliedenergistics2:material:56>, <nuclearcraft:part:3>, <appliedenergistics2:material:56>], [<nuclearcraft:alloy:1>, <appliedenergistics2:material:56>, <nuclearcraft:alloy:1>]]);
recipes.addShaped(<appliedenergistics2:material:56>, [[<nuclearcraft:alloy:1>, <appliedenergistics2:material:23>, <nuclearcraft:alloy:1>],[<appliedenergistics2:material:55>, <nuclearcraft:part:2>, <appliedenergistics2:material:55>], [<nuclearcraft:alloy:1>, <appliedenergistics2:material:55>, <nuclearcraft:alloy:1>]]);
recipes.addShaped(<appliedenergistics2:material:55>, [[<nuclearcraft:alloy:1>, <appliedenergistics2:material:23>, <nuclearcraft:alloy:1>],[<appliedenergistics2:material:54>, <nuclearcraft:part:1>, <appliedenergistics2:material:54>], [<nuclearcraft:alloy:1>, <appliedenergistics2:material:54>, <nuclearcraft:alloy:1>]]);
recipes.addShaped(<extrautils2:machine>.withTag({Type: "extrautils2:generator_netherstar"}), [[<minecraft:skull:1>, <minecraft:skull:1>, <minecraft:skull:1>],[<minecraft:skull:1>, <thaumcraft:primordial_pearl>, <minecraft:skull:1>], [<extrautils2:ingredients:11>, <enderio:item_material:55>, <extrautils2:ingredients:11>]]);
recipes.addShaped(<appliedenergistics2:material:38>, [[<nuclearcraft:alloy:1>, <appliedenergistics2:material:24>, <nuclearcraft:alloy:1>],[<appliedenergistics2:material:37>, <nuclearcraft:part:3>, <appliedenergistics2:material:37>], [<nuclearcraft:alloy:1>, <appliedenergistics2:material:37>, <nuclearcraft:alloy:1>]]);
recipes.addShaped(<appliedenergistics2:material:37>, [[<nuclearcraft:alloy:1>, <appliedenergistics2:material:24>, <nuclearcraft:alloy:1>],[<appliedenergistics2:material:36>, <nuclearcraft:part:2>, <appliedenergistics2:material:36>], [<nuclearcraft:alloy:1>, <appliedenergistics2:material:36>, <nuclearcraft:alloy:1>]]);
recipes.addShaped(<appliedenergistics2:material:35>, [[<nuclearcraft:alloy:1>, <nuclearcraft:part>, <nuclearcraft:alloy:1>],[<nuclearcraft:part>, <appliedenergistics2:material:22>, <nuclearcraft:part>], [<nuclearcraft:alloy:1>, <nuclearcraft:part>, <nuclearcraft:alloy:1>]]);
recipes.addShaped(<appliedenergistics2:material:36>, [[<nuclearcraft:alloy:1>, <appliedenergistics2:material:23>, <nuclearcraft:alloy:1>],[<appliedenergistics2:material:35>, <nuclearcraft:part:1>, <appliedenergistics2:material:35>], [<nuclearcraft:alloy:1>, <appliedenergistics2:material:35>, <nuclearcraft:alloy:1>]]);
recipes.addShaped(<draconicevolution:fusion_crafting_core>, [[<enderio:item_material:54>, <nuclearcraft:cooler:7>, <enderio:item_material:54>],[<nuclearcraft:cooler:7>, <draconicevolution:wyvern_core>, <nuclearcraft:cooler:7>], [<enderio:item_material:54>, <woot:cell:2>, <enderio:item_material:54>]]);
recipes.addShaped(<nuclearcraft:reactor_casing_transparent> * 4, [[<enderio:block_fused_quartz>, <nuclearcraft:part:3>, <enderio:block_fused_quartz>],[<nuclearcraft:part:3>, <nuclearcraft:alloy:1>, <nuclearcraft:part:3>], [<enderio:block_fused_quartz>, <nuclearcraft:part:3>, <enderio:block_fused_quartz>]]);
//recipes.addShaped(<nuclearcraft:fission_block> * 4, [[null, <nuclearcraft:part:3>, null],[<nuclearcraft:part:3>, <nuclearcraft:alloy:1>, <nuclearcraft:part:3>], [null, <nuclearcraft:part:3>, null]]);
recipes.addShaped(<nuclearcraft:fission_controller_new_idle>, [[<nuclearcraft:part:1>, <nuclearcraft:part:5>, <nuclearcraft:part:1>],[<nuclearcraft:nuclear_furnace_idle>, <enderio:item_material:55>, <nuclearcraft:nuclear_furnace_idle>], [<nuclearcraft:part:1>, <nuclearcraft:part:5>, <nuclearcraft:part:1>]]);
//recipes.addShaped(<draconicevolution:crafting_injector>, [[<avaritia:resource>, <draconicevolution:draconic_core>, <avaritia:resource>],[<thaumicbases:oldiron>, <avaritia:singularity>, <thaumicbases:oldiron>], [<thaumicbases:oldiron>, <thaumicbases:oldiron>, <thaumicbases:oldiron>]]);
//recipes.addShaped(<appliedenergistics2:material:57>, [[<nuclearcraft:alloy:1>, <appliedenergistics2:material:23>, <nuclearcraft:alloy:1>],[<appliedenergistics2:material:56>, <avaritia:singularity:1>, <appliedenergistics2:material:56>], [<nuclearcraft:alloy:1>, <appliedenergistics2:material:56>, <nuclearcraft:alloy:1>]]);
//recipes.addShaped(<appliedenergistics2:material:56>, [[<nuclearcraft:alloy:1>, <appliedenergistics2:material:23>, <nuclearcraft:alloy:1>],[<appliedenergistics2:material:55>, <avaritia:singularity:3>, <appliedenergistics2:material:55>], [<nuclearcraft:alloy:1>, <appliedenergistics2:material:55>, <nuclearcraft:alloy:1>]]);
//recipes.addShaped(<appliedenergistics2:material:55>, [[<nuclearcraft:alloy:1>, <appliedenergistics2:material:23>, <nuclearcraft:alloy:1>],[<appliedenergistics2:material:54>, <avaritia:singularity>, <appliedenergistics2:material:54>], [<nuclearcraft:alloy:1>, <appliedenergistics2:material:54>, <nuclearcraft:alloy:1>]]);
//recipes.addShaped(<extrautils2:machine>, [[<minecraft:skull:1>.anyDamage(), <minecraft:skull:1>, <minecraft:skull:1>],[<minecraft:skull:1>, <avaritia:endest_pearl>, <minecraft:skull:1>], [<extrautils2:ingredients:11>, <enderio:item_material:55>, <extrautils2:ingredients:11>]]);
//recipes.addShaped(<extrautils2:angelring>, [[<nuclearcraft:reactor_casing_transparent>.anyDamage(), <thaumadditions:mithrillium_ingot>, <nuclearcraft:reactor_casing_transparent>],[<thaumadditions:mithrillium_ingot>, <extrautils2:chickenring:1>, <thaumadditions:mithrillium_ingot>], [<enderio:item_material:19>, <thaumadditions:mithrillium_ingot>, <enderio:item_material:19>]]);
recipes.addShaped(<wct:wct>, [[<appliedenergistics2:wireless_terminal>.anyDamage(), <appliedenergistics2:material:9>, null],[<appliedenergistics2:part:360>, <avaritia:endest_pearl>, null], [null, null, null]]);
recipes.addShaped(<mysticalagriculture:void_metal_seeds>, [[<thaumicbases:thauminite_ingot>, <mysticalagradditions:insanium>, <thaumicbases:thauminite_ingot>],[<mysticalagradditions:insanium>, <mysticalagradditions:insanium:1>, <mysticalagradditions:insanium>], [<thaumicbases:thauminite_ingot>, <mysticalagradditions:insanium>, <thaumicbases:thauminite_ingot>]]);
recipes.addShaped(<translocators:translocator_part>, [[<redstonefluxarsenal:itemrfenergizedingot>, <randomthings:stableenderpearl>, <redstonefluxarsenal:itemrfenergizedingot>],[<thaumcraft:ingot>, <enderio:item_item_conduit>, <thaumcraft:ingot>], [<redstonefluxarsenal:itemrfenergizedingot>, <thaumcraft:ingot>, <redstonefluxarsenal:itemrfenergizedingot>]]);
recipes.addShaped(<projecte:item.pe_gem_armor_1>, [[<projecte:item.pe_rm_armor_1>, <projecte:item.pe_klein_star:5>, null],[<projecte:item.pe_black_hole>, <thaumictinkerer:cleaning_talisman>, null], [null, null, null]]);
//recipes.addShaped(<progressivealchemy:condensertiered_3>, [[<projecte:item.pe_covalence_dust:2>, <projecte:item.pe_covalence_dust:2>, <projecte:item.pe_covalence_dust:2>],[<appliedenergistics2:sky_stone_block>, <enderio:item_material:41>, <appliedenergistics2:sky_stone_block>], [<thaumcraft:ingot>, <progressivealchemy:condensertiered_2>, <thaumcraft:ingot>]]);
//recipes.addShaped(<progressivealchemy:condensertiered_1>, [[<projecte:item.pe_covalence_dust>, <projecte:item.pe_covalence_dust>, <projecte:item.pe_covalence_dust>],[<appliedenergistics2:sky_stone_block>, <enderio:item_basic_capacitor>, <appliedenergistics2:sky_stone_block>], [<minecraft:iron_ingot>, <projecte:alchemical_chest>, <minecraft:iron_ingot>]]);
//recipes.addShaped(<progressivealchemy:condensertiered_2>, [[<projecte:item.pe_covalence_dust:1>, <projecte:item.pe_covalence_dust:1>, <projecte:item.pe_covalence_dust:1>],[<appliedenergistics2:sky_stone_block>, <enderio:item_material:40>, <appliedenergistics2:sky_stone_block>], [<minecraft:gold_ingot>, <progressivealchemy:condensertiered_1>, <minecraft:gold_ingot>]]);
recipes.addShaped(<progressivealchemy:condensertiered_4>, [[<thaumcraft:salis_mundus>, <thaumcraft:salis_mundus>, <thaumcraft:salis_mundus>],[<appliedenergistics2:sky_stone_block>, <enderio:item_material:42>, <appliedenergistics2:sky_stone_block>], [<thaumicbases:thauminite_ingot>, <progressivealchemy:condensertiered_3>, <thaumicbases:thauminite_ingot>]]);
recipes.addShaped(<progressivealchemy:condensertiered_5>, [[<thaumcraft:salis_mundus>, <thaumcraft:salis_mundus>, <thaumcraft:salis_mundus>],[<appliedenergistics2:sky_stone_block>, <draconicevolution:draconic_core>, <appliedenergistics2:sky_stone_block>], [<thaumcraft:ingot:1>, <progressivealchemy:condensertiered_4>, <thaumcraft:ingot:1>]]);
recipes.addShaped(<progressivealchemy:condensertiered_6>, [[<thaumcraft:salis_mundus>, <thaumcraft:salis_mundus>, <thaumcraft:salis_mundus>],[<appliedenergistics2:sky_stone_block>, <draconicevolution:wyvern_core>, <appliedenergistics2:sky_stone_block>], [<thaumadditions:mithrillium_ingot>, <progressivealchemy:condensertiered_5>, <thaumadditions:mithrillium_ingot>]]);
recipes.addShaped(<progressivealchemy:condensertiered_7>, [[<thaumcraft:salis_mundus>, <thaumcraft:salis_mundus>, <thaumcraft:salis_mundus>],[<appliedenergistics2:sky_stone_block>, <draconicevolution:awakened_core>, <appliedenergistics2:sky_stone_block>], [<thaumadditions:adaminite_ingot>, <progressivealchemy:condensertiered_6>, <thaumadditions:adaminite_ingot>]]);
recipes.addShaped(<progressivealchemy:condensertiered_8>, [[<thaumcraft:salis_mundus>, <thaumcraft:salis_mundus>, <thaumcraft:salis_mundus>],[<appliedenergistics2:sky_stone_block>, <draconicevolution:chaotic_core>, <appliedenergistics2:sky_stone_block>], [<thaumadditions:mithminite_ingot>, <progressivealchemy:condensertiered_7>, <thaumadditions:mithminite_ingot>]]);
recipes.addShaped(<appliedenergistics2:energy_acceptor>, [[<thaumadditions:adaminite_ingot>, <draconicevolution:wyvern_energy_core>, <thaumadditions:adaminite_ingot>],[<draconicevolution:wyvern_energy_core>, <draconicevolution:ender_energy_manipulator>, <draconicevolution:wyvern_energy_core>], [<thaumadditions:adaminite_ingot>, <draconicevolution:wyvern_energy_core>, <thaumadditions:adaminite_ingot>]]);
recipes.addShaped(<randomthings:spectrekey>, [[<enderutilities:enderpart:2>, null, null],[<enderutilities:enderpart:2>, <randomthings:stableenderpearl>, null], [null, null, <enderutilities:enderpart:2>]]);
recipes.addShaped(<thaumcraft:brain>, [[<minecraft:rotten_flesh>, <minecraft:rotten_flesh>, <minecraft:rotten_flesh>],[<minecraft:rotten_flesh>, <foodfunk:rotten_food>, <minecraft:rotten_flesh>], [<minecraft:rotten_flesh>, <minecraft:rotten_flesh>, <minecraft:rotten_flesh>]]);
recipes.addShapeless(<enderio:item_material:33>, [<ore:dustQuartz>]);
recipes.addShaped(<projecte:alchemical_chest>, [[<projecte:item.pe_covalence_dust>, <projecte:item.pe_covalence_dust:1>, <projecte:item.pe_covalence_dust:2>],[<appliedenergistics2:smooth_sky_stone_block>, <enderio:item_material:41>, <appliedenergistics2:smooth_sky_stone_block>], [<redstonefluxarsenal:itemrfdarkingot>, <appliedenergistics2:sky_stone_chest>, <redstonefluxarsenal:itemrfdarkingot>]]);
recipes.addShaped(<enderio:item_power_conduit>, [[<enderio:item_material:4>, <enderio:item_material:4>, <enderio:item_material:4>],[<enderio:item_alloy_ingot:4>, <enderio:item_alloy_ingot:4>, <enderio:item_alloy_ingot:4>], [<enderio:item_material:4>, <enderio:item_material:4>, <enderio:item_material:4>]]);
recipes.addShaped(<enderio:item_power_conduit:1>, [[<enderio:item_material:4>, <enderio:item_material:4>, <enderio:item_material:4>],[<enderio:item_alloy_ingot:1>, <enderio:item_power_conduit>, <enderio:item_alloy_ingot:1>], [<enderio:item_material:4>, <enderio:item_material:4>, <enderio:item_material:4>]]);
recipes.addShaped(<enderio:item_power_conduit:1>, [[<enderio:item_material:4>, <enderio:item_material:4>, <enderio:item_material:4>],[<enderio:item_alloy_ingot:1>, <enderio:item_alloy_ingot:1>, <enderio:item_alloy_ingot:1>], [<enderio:item_material:4>, <enderio:item_material:4>, <enderio:item_material:4>]]);
recipes.addShaped(<enderio:item_power_conduit:2>, [[<enderio:item_material:4>, <enderio:item_material:4>, <enderio:item_material:4>],[<enderio:item_alloy_ingot:2>, <enderio:item_power_conduit:1>, <enderio:item_alloy_ingot:2>], [<enderio:item_material:4>, <enderio:item_material:4>, <enderio:item_material:4>]]);
recipes.addShaped(<enderio:item_power_conduit:2>, [[<enderio:item_material:4>, <enderio:item_material:4>, <enderio:item_material:4>],[<enderio:item_alloy_ingot:2>, <enderio:item_alloy_ingot:2>, <enderio:item_alloy_ingot:2>], [<enderio:item_material:4>, <enderio:item_material:4>, <enderio:item_material:4>]]);
recipes.addShaped(<appliedenergistics2:drive>, [[<nuclearcraft:alloy:5>, <appliedenergistics2:material:24>, <nuclearcraft:alloy:5>],[<appliedenergistics2:part:16>, <enderio:item_material:1>, <appliedenergistics2:part:16>], [<ore:ingotDarkSteel>, <appliedenergistics2:material:24>, <ore:ingotDarkSteel>]]);
recipes.addShaped(<appliedenergistics2:charger>, [[<redstonefluxarsenal:itemrfdarkingot>, <ore:crystalFluix>, <redstonefluxarsenal:itemrfdarkingot>],[<redstonefluxarsenal:itemrfdarkingot>, null, null], [<redstonefluxarsenal:itemrfdarkingot>, <ore:crystalFluix>, <redstonefluxarsenal:itemrfdarkingot>]]);
recipes.addShaped(<enderio:block_simple_sag_mill>, [[<minecraft:flint>, <minecraft:flint>, <minecraft:flint>],[<minecraft:iron_ingot>, <enderio:item_material>, <minecraft:iron_ingot>], [<ore:gearStone>, <appliedenergistics2:grindstone>, <ore:gearStone>]]);
//recipes.addShaped(<exnihilocreatio:block_end_cake>, [[<randomthings:stableenderpearl>, <minecraft:ender_eye>, <randomthings:stableenderpearl>],[<randomthings:stableenderpearl>, <xlfoodmod:oreo_cake>, <randomthings:stableenderpearl>], [<endreborn:item_advanced_ender_pearl>, <chisel:voidstone>, <endreborn:item_advanced_ender_pearl>]]);
recipes.addShaped(<storagenetwork:remote:1>, [[<endreborn:item_advanced_ender_pearl>, <ironjetpacks:advanced_coil>, <endreborn:item_advanced_ender_pearl>],[<redstonefluxarsenal:itemrfdarkingot>, <storagenetwork:remote>, <redstonefluxarsenal:itemrfdarkingot>], [<endreborn:item_advanced_ender_pearl>, <ironjetpacks:advanced_coil>, <endreborn:item_advanced_ender_pearl>]]);
recipes.addShaped(<storagenetwork:remote>, [[null, <redstonefluxarsenal:itemrfdarkingot>, null],[<endreborn:item_advanced_ender_pearl>, <storagenetwork:kabel>, <endreborn:item_advanced_ender_pearl>], [null, <redstonefluxarsenal:itemrfdarkingot>, null]]);
recipes.addShaped(<simplevoidworld:portal>, [[<chisel:voidstone>, <endreborn:item_advanced_ender_pearl>, <chisel:voidstone>],[<endreborn:item_advanced_ender_pearl>, <aether:zanite_block>, <endreborn:item_advanced_ender_pearl>], [<chisel:voidstone>, <endreborn:item_advanced_ender_pearl>, <chisel:voidstone>]]);
recipes.addShaped(<enderio:item_item_conduit>, [[<enderio:item_material:4>, <enderio:item_material:4>, <enderio:item_material:4>],[<enderio:item_alloy_nugget:5>, <enderio:item_alloy_nugget:5>, <enderio:item_alloy_nugget:5>], [<enderio:item_material:4>, <enderio:item_material:4>, <enderio:item_material:4>]]);
//recipes.addShapeless(<aether:holystone>, [<aether:holystone_rock>,<aether:holystone_rock>,<aether:holystone_rock>,<aether:holystone_rock>]);
recipes.addShaped(<minecraft:paper>, [[null, null, null],[<excompressum:wood_chippings>, <excompressum:wood_chippings>, <excompressum:wood_chippings>], [<excompressum:wood_chippings>, <excompressum:wood_chippings>, <excompressum:wood_chippings>]]);
recipes.addShaped(<minecraft:cauldron>, [[<nuclearcraft:alloy:5>, null, <nuclearcraft:alloy:5>],[<ore:ingotSteel>, null, <ore:ingotSteel>], [<nuclearcraft:alloy:5>, <ore:ingotSteel>, <nuclearcraft:alloy:5>]]);
recipes.addShaped(<projecte:item.pe_tome>, [[<avaritiatweaks:enhancement_crystal>, <draconicevolution:reactor_core>, <avaritiatweaks:enhancement_crystal>],[<draconicevolution:chaotic_core>, <questbook:itemquestbook>, <draconicevolution:chaotic_core>], [<thaumadditions:mithminite_plate>, <ore:crystalAethium>, <thaumadditions:mithminite_plate>]]);
recipes.addShaped(<nuclearcraft:alloy_furnace_idle>, [[<nuclearcraft:ingot:2>, <enderio:item_basic_capacitor>, <nuclearcraft:ingot:2>],[<redstonefluxarsenal:itemrfdarkingot>, <nuclearcraft:part>, <redstonefluxarsenal:itemrfdarkingot>], [<nuclearcraft:part>, <thaumadditions:crafting_furnace>, <nuclearcraft:part>]]);
recipes.addShaped(<nuclearcraft:manufactory_idle>, [[<nuclearcraft:ingot:2>, <enderio:item_basic_capacitor>, <nuclearcraft:ingot:2>],[<redstonefluxarsenal:itemrfdarkingot>, <nuclearcraft:ingot:2>, <redstonefluxarsenal:itemrfdarkingot>], [<nuclearcraft:ingot:2>, <appliedenergistics2:grindstone>, <nuclearcraft:ingot:2>]]);
recipes.addShaped(<nuclearcraft:upgrade>, [[<nuclearcraft:alloy:2>, <nuclearcraft:gem_dust:1>, <nuclearcraft:alloy:2>],[<nuclearcraft:gem_dust:1>, <enderio:item_basic_capacitor>, <nuclearcraft:gem_dust:1>], [<nuclearcraft:alloy:2>, <nuclearcraft:gem_dust:1>, <nuclearcraft:alloy:2>]]);
recipes.addShaped(<storagenetwork:master>, [[<fluxnetworks:fluxblock>, <storagenetwork:kabel>, <fluxnetworks:fluxblock>],[<storagenetwork:kabel>, <enderio:item_material:41>, <storagenetwork:kabel>], [<fluxnetworks:fluxblock>, <storagenetwork:kabel>, <fluxnetworks:fluxblock>]]);
recipes.addShaped(<storagenetwork:kabel> * 4, [[<enderio:item_material:4>, <enderio:item_material:4>, <enderio:item_material:4>],[<enderio:item_alloy_nugget>, <enderio:item_alloy_nugget>, <enderio:item_alloy_nugget>], [<enderio:item_material:4>, <enderio:item_material:4>, <enderio:item_material:4>]]);
recipes.addShaped(<storagenetwork:request>, [[<nuclearcraft:part>, <storagenetwork:kabel>, <nuclearcraft:part>],[<storagenetwork:kabel>, <enderio:item_material:40>, <storagenetwork:kabel>], [<nuclearcraft:part>, <storagenetwork:kabel>, <nuclearcraft:part>]]);
recipes.addShaped(<extrautils2:grocket>, [[null, null, null],[<redstonefluxarsenal:itemrfenergizedingot>, <extrautils2:pipe>, <redstonefluxarsenal:itemrfenergizedingot>], [<nuclearcraft:part>, <enderutilities:storage_0:3>, <nuclearcraft:part>]]);
recipes.addShaped(<extrautils2:bagofholding>, [[<extrautils2:ingredients:12>, <extrautils2:ingredients:12>, <extrautils2:ingredients:12>],[<enderutilities:storage_0:3>, <thaumicbases:dustblock>, <enderutilities:storage_0:3>], [<extrautils2:ingredients:12>, <extrautils2:ingredients:12>, <extrautils2:ingredients:12>]]);
recipes.addShaped(<extrautils2:machine>.withTag({Type: "extrautils2:furnace"}), [[<nuclearcraft:ingot:2>, <thaumadditions:crafting_furnace>, <nuclearcraft:ingot:2>],[<redstonefluxarsenal:itemrfdarkingot>, <nuclearcraft:part>, <redstonefluxarsenal:itemrfdarkingot>], [<nuclearcraft:part>, <enderio:item_basic_capacitor>, <nuclearcraft:part>]]);
recipes.addShaped(<extrautils2:machine>.withTag({Type: "extrautils2:crusher"}), [[<nuclearcraft:ingot:2>, <appliedenergistics2:grindstone>, <nuclearcraft:ingot:2>],[<redstonefluxarsenal:itemrfdarkingot>, <nuclearcraft:part>, <redstonefluxarsenal:itemrfdarkingot>], [<nuclearcraft:part>, <enderio:item_basic_capacitor>, <nuclearcraft:part>]]);
recipes.addShaped(<enderio:item_material:51>, [[<enderio:item_material:32>, <thaumcraft:salis_mundus>, <enderio:item_material:48>],[<enderio:item_material:33>, <enderio:item_material:50>, <enderio:item_material:33>], [<enderio:item_material:48>, <thaumcraft:salis_mundus>, <enderio:item_material:32>]]);
//recipes.addShaped(<extrautils2:angelring>, [[<mysticalagriculture:soul_glass>, <extrautils2:ingredients:12>, <mysticalagriculture:soul_glass>],[<extrautils2:ingredients:12>, <extrautils2:chickenring:1>, <extrautils2:ingredients:12>], [<enderio:item_material:19>, <extrautils2:ingredients:12>, <enderio:item_material:19>]]);
recipes.addShaped(<mysticalagriculture:crafting:32>, [[<thaumcraft:salis_mundus>, <mysticalagriculture:crafting:5>, <thaumcraft:salis_mundus>],[<mysticalagriculture:crafting:5>, <minecraft:iron_ingot>, <mysticalagriculture:crafting:5>], [<thaumcraft:salis_mundus>, <mysticalagriculture:crafting:5>, <thaumcraft:salis_mundus>]]);
recipes.addShaped(<mysticalagriculture:supremium_chestplate>, [[<mysticalagriculture:crafting:37>, <draconicevolution:ender_energy_manipulator>, <mysticalagriculture:crafting:37>],[<mysticalagriculture:crafting:37>, <mysticalagriculture:gear:9>, <mysticalagriculture:crafting:37>], [<mysticalagriculture:crafting:37>, <mysticalagriculture:crafting:37>, <mysticalagriculture:crafting:37>]]);
recipes.addShaped(<equivalentenergistics:emc_condenser:3>, [[<thaumadditions:mithminite_ingot>, <thaumadditions:mithminite_ingot>, <thaumadditions:mithminite_ingot>],[<enderio:item_material:16>, <equivalentenergistics:emc_condenser:2>, <enderio:item_material:19>], [<thaumadditions:mithminite_ingot>, <thaumadditions:mithminite_ingot>, <thaumadditions:mithminite_ingot>]]);
recipes.addShaped(<equivalentenergistics:emc_condenser:2>, [[<thaumadditions:mithrillium_ingot>, <thaumadditions:mithrillium_ingot>, <thaumadditions:mithrillium_ingot>],[<enderio:item_material:16>, <equivalentenergistics:emc_condenser:1>, <enderio:item_material:19>], [<thaumadditions:mithrillium_ingot>, <thaumadditions:mithrillium_ingot>, <thaumadditions:mithrillium_ingot>]]);
recipes.addShaped(<equivalentenergistics:emc_condenser:1>, [[<thaumcraft:ingot>, <thaumcraft:ingot>, <thaumcraft:ingot>],[<enderio:item_material:16>, <equivalentenergistics:emc_condenser>, <enderio:item_material:19>], [<thaumcraft:ingot>, <thaumcraft:ingot>, <thaumcraft:ingot>]]);
//recipes.addShaped(<minecraft:furnace>, [[<minecraft:cobblestone>, <minecraft:cobblestone>, <minecraft:cobblestone>],[<minecraft:cobblestone>, <minecraft:cobblestone>, <minecraft:cobblestone>], [<exnihilocreatio:item_material:1>, <exnihilocreatio:item_material:1>, <exnihilocreatio:item_material:1>]]);
recipes.addShaped(<aether:holystone_furnace>, [[<exnihilocreatio:item_material:1>, <exnihilocreatio:item_material:1>, <exnihilocreatio:item_material:1>],[<aether:holystone>, <exnihilocreatio:item_material:1>, <aether:holystone>], [<aether:holystone>, <aether:holystone>, <aether:holystone>]]);
recipes.addShaped(<mysticalagriculture:crafting:16>, [[<thaumcraft:salis_mundus>, <mysticalagriculture:crafting:5>, <thaumcraft:salis_mundus>],[<mysticalagriculture:crafting:5>, <minecraft:wheat_seeds>, <mysticalagriculture:crafting:5>], [<thaumcraft:salis_mundus>, <mysticalagriculture:crafting:5>, <thaumcraft:salis_mundus>]]);
recipes.addShaped(<enderio:item_broken_spawner>, [[<ore:itemEnhancedChassiParts>, <enderio:item_material:68>, <ore:itemEnhancedChassiParts>],[<enderio:item_material:68>, <enderio:item_material:53>, <enderio:item_material:68>], [<enderio:item_material:68>, <enderio:item_material:68>, <enderio:item_material:68>]]);
recipes.addShapeless(<thaumcraft:primordial_pearl>, [<thaumcraft:salis_mundus>,<minecraft:nether_star>]);
recipes.addShaped(<extrautils2:grocket:2>, [[null, null, null],[<redstonefluxarsenal:itemrfenergizedingot>, <extrautils2:pipe>, <redstonefluxarsenal:itemrfenergizedingot>], [<appliedenergistics2:smooth_sky_stone_block>, <minecraft:bucket>, <appliedenergistics2:smooth_sky_stone_block>]]);
recipes.addShaped(<extrautils2:pipe> * 16, [[null, null, null],[<minecraft:glass>, <redstonefluxarsenal:itemrfenergizedingot>, <minecraft:glass>], [null, null, null]]);
recipes.addShaped(<appliedenergistics2:inscriber>, [[<enderio:item_alloy_ingot:6>, <minecraft:sticky_piston>, <enderio:item_alloy_ingot:6>],[<enderio:item_basic_capacitor:2>, null, <enderio:item_alloy_ingot:6>], [<enderio:item_alloy_ingot:6>, <minecraft:sticky_piston>, <enderio:item_alloy_ingot:6>]]);
recipes.addShaped(<minecraft:leather>, [[<foodfunk:rotten_food>, <foodfunk:rotten_food>, <foodfunk:rotten_food>],[<foodfunk:rotten_food>, <minecraft:rotten_flesh>, <foodfunk:rotten_food>], [<foodfunk:rotten_food>, <foodfunk:rotten_food>, <foodfunk:rotten_food>]]);
recipes.addShaped(<minecraft:rotten_flesh>, [[<foodfunk:rotten_food>, <foodfunk:rotten_food>, <foodfunk:rotten_food>],[<foodfunk:rotten_food>, <foodfunk:rotten_food>, <foodfunk:rotten_food>], [<foodfunk:rotten_food>, <foodfunk:rotten_food>, <foodfunk:rotten_food>]]);
recipes.addShapeless(<excompressum:bait:11>, [<minecraft:wheat>,<thaumcraft:salis_mundus>]);
recipes.addShapeless(<minecraft:slime_ball>, [<exnihilocreatio:item_material:1>,<minecraft:dye:10>]);
//recipes.addShapeless(<aether:skyroot_planks>, [<aether:skyroot_slab>,<aether:skyroot_slab>]);
//recipes.addShaped(<thaumicterminal:item_part>, [[<appliedenergistics2:part:380>, <thaumcraft:arcane_workbench>, null],[<appliedenergistics2:material:23>, null, null], [null, null, null]]);
recipes.addShaped(<projecte:item.pe_philosophers_stone>, [[<thaumcraft:salis_mundus>, <appliedenergistics2:material:45>, <thaumcraft:salis_mundus>],[<appliedenergistics2:material:45>, <draconicevolution:draconic_core>, <appliedenergistics2:material:45>], [<thaumcraft:salis_mundus>, <appliedenergistics2:material:45>, <thaumcraft:salis_mundus>]]);
//recipes.addShaped(<exnihilocreatio:block_crucible_wood>, [[<aether:skyroot_log>, null, <aether:skyroot_log>],[<aether:skyroot_log>, null, <aether:skyroot_log>], [<aether:skyroot_log>, <aether:skyroot_slab>, <aether:skyroot_log>]]);
//recipes.addShaped(<exnihilocreatio:block_barrel1>, [[<ore:holystone>, null, <ore:holystone>],[<ore:holystone>, null, <ore:holystone>], [<ore:holystone>, <aether:holystone_slab>, <ore:holystone>]]);
//recipes.addShaped(<exnihilocreatio:block_barrel0>, [[<ore:skyrootplanks>, null, <ore:skyrootplanks>],[<ore:skyrootplanks>, null, <ore:skyrootplanks>], [<ore:skyrootplanks>, <aether:skyroot_slab>, <ore:skyrootplanks>]]);
//File End
